Repository UnBArqDsw2022-2/2022.2_G2_RiFA, pull requests merged in 2022-11, with the labels that each got.

#11 #1 Adicionando documentação sobre Rich Picture.
  docs/Base/rich-picture.md
  docs/_sidebar.md
Labels: documentation

#12 #5 - Diagrama Causa-Efeito
  docs/Base/diagramaCausaEfeito.md
  docs/_sidebar.md
  docs/assets/diagramaCausaEfeito.png
Labels: documentation

#17 BASE - Metodologias
  docs/Base/1.2.ProcessosMetodologiasAbordagens.md
  docs/Base/metodologiasAdotadas.md
  docs/Base/processos.md
  docs/README.md
  docs/_coverpage.md
  docs/_sidebar.md
  docs/assets/arquivoEducacional.png
  docs/assets/ask.png
  docs/assets/bolaInicioProcesso.png
  docs/assets/comentario.png
  docs/assets/email.png
  docs/assets/endProcess.png
  docs/assets/fileOnline.png
  docs/assets/fileTeam.png
  docs/assets/gatewayAsk.png
  docs/assets/github.png
  docs/assets/group.png
  docs/assets/guilhermeFoto.jpg
  docs/assets/interacao.png
  docs/assets/parallel.png
  docs/assets/process.png
  docs/assets/provedorDeDados.png
  docs/assets/roda.jpg
  docs/assets/sprint.svg
  docs/assets/task.png
  docs/index.html
Labels: documentation

#18 #8 BASE - Plano de Riscos
  docs/Base/PlanoDeRiscos.md
  docs/_sidebar.md
Labels: documentation

#22 5w2h simplificado
  docs/Base/5w2h.md
  docs/_sidebar.md
Labels: documentation

#24 Mudança no custo do projeto no 5W2H
  docs/Base/5w2h.md
Labels: enhancement

#26 correções ortográficas
  docs/ArquiteturaReutilizacao/4.1.PadroesArquiteturais.md
  docs/ArquiteturaReutilizacao/4.2.ReutilizacaoDeSoftware.md
  docs/Base/1.1.AbordagemNaoEspecifica.md
  docs/Base/artefatos-design-sprint/PlanoDeRiscos.md
  docs/Base/artefatos-design-sprint/lexicos.md
  docs/Base/artefatos-design-sprint/mapaMental.md
  docs/Base/artefatos-design-sprint/rich-picture.md
  docs/Base/designSprint.md
  docs/Base/extra/brainstorming.md
  docs/Base/metodologiasAdotadas.md
  docs/Base/pre-rastreabilidade/estimativaCustoTempo.md
  docs/Base/processos.md
Labels: documentation

#29 Adicionando diretrizes ao Contributing.md
  CONTRIBUTING.md
Labels: documentation, enhancement
